// CustomLabelStyles.js
const styles = {
  title: {
    color: '#194A9F',
    fontSize: '20px',
    fontWeight: 600,
    lineHeight: 'normal',
    width: '100%',
    textAlign: 'left',
    marginBottom: '1rem',
  },
  titleBlack: {
    fontSize: '20px',
    fontWeight: 600,
    lineHeight: 'normal',
    width: '100%',
    textAlign: 'left',
    marginBottom: '1rem',
  },
  large: {
    color: '#194A9F',
    fontSize: '20px',
    fontWeight: 600,
    lineHeight: 'normal',
    width: '100%',
    textAlign: 'left',
    marginBottom: '1rem',
    paddingTop: '3%',
  },
  medium: {
    color: '#194A9F',
    fontSize: '15px',
    fontWeight: 600,
    lineHeight: 'normal',
    width: '100%',
    textAlign: 'left',
    marginBottom: '1rem',
    paddingTop: '2%',
  },
  mediumTrad: {
    color: '#194A9F',
    fontSize: '15px',
    fontWeight: 600,
    lineHeight: 'normal',
    width: '100%',
    textAlign: 'left',
    marginBottom: '1rem',
    paddingTop: '6%',
  },
  normal: {
    fontSize: '15px',
    fontWeight: 600,
    lineHeight: 'normal',
    width: '100%',
    textAlign: 'left',
    marginBottom: '1rem',
    paddingTop: '2%',
  },
  normalHeader: {
    fontSize: '18px',
    fontWeight: 600,
    lineHeight: 'normal',
    width: '100%',
    textAlign: 'left',
    marginBottom: '1rem',
    paddingTop: '2%',
  },
  light: {
    fontSize: '15px',
    fontWeight: 500,
    lineHeight: 'normal',
    width: '100%',
    textAlign: 'left',
    marginBottom: '1rem',
    paddingTop: '2%',
  },
  headingMain: {
    fontSize: '32px',

  },
  allSet: {
    color: '#040308',
    fontSize: '2rem',
    fontStyle: 'italic',
    fontWeight: 300,
    lineHeight: 'normal',
  }
};

export default styles;
